/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PTB5 (number 12), LED1
  @{ */
#define BOARD_INITPINS_LED1_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_LED1_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_LED1_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LED1_GPIO_PIN 13U     /*!<@brief PORTA pin index: 13 */
#define BOARD_INITPINS_LED1_PORT PORTB       /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED1_PIN 5U           /*!<@brief PORTB pin index: 5 */
#define BOARD_INITPINS_LED1_CHANNEL 13       /*!<@brief GPIOA GPIO channel: 13 */
#define BOARD_INITPINS_LED1_PIN_NAME PTB5    /*!<@brief Pin name */
#define BOARD_INITPINS_LED1_LABEL "LED1"     /*!<@brief Label */
#define BOARD_INITPINS_LED1_NAME "LED1"      /*!<@brief Identifier name */
                                             /* @} */

/*! @name PTC2 (number 15), LED3
  @{ */
#define BOARD_INITPINS_LED3_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_LED3_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_LED3_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LED3_GPIO_PIN 18U     /*!<@brief PORTA pin index: 18 */
#define BOARD_INITPINS_LED3_PORT PORTC       /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED3_PIN 2U           /*!<@brief PORTC pin index: 2 */
#define BOARD_INITPINS_LED3_CHANNEL 18       /*!<@brief GPIOA GPIO channel: 18 */
#define BOARD_INITPINS_LED3_PIN_NAME PTC2    /*!<@brief Pin name */
#define BOARD_INITPINS_LED3_LABEL "LED3"     /*!<@brief Label */
#define BOARD_INITPINS_LED3_NAME "LED3"      /*!<@brief Identifier name */
                                             /* @} */

/*! @name PTC3 (number 14), LED2
  @{ */
#define BOARD_INITPINS_LED2_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_LED2_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_LED2_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_LED2_GPIO_PIN 19U     /*!<@brief PORTA pin index: 19 */
#define BOARD_INITPINS_LED2_PORT PORTC       /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED2_PIN 3U           /*!<@brief PORTC pin index: 3 */
#define BOARD_INITPINS_LED2_CHANNEL 19       /*!<@brief GPIOA GPIO channel: 19 */
#define BOARD_INITPINS_LED2_PIN_NAME PTC3    /*!<@brief Pin name */
#define BOARD_INITPINS_LED2_LABEL "LED2"     /*!<@brief Label */
#define BOARD_INITPINS_LED2_NAME "LED2"      /*!<@brief Identifier name */
                                             /* @} */

/*! @name PTE1 (number 39), OFF_SWITCH
  @{ */
#define BOARD_INITPINS_OFF_SWITCH_PERIPHERAL GPIOB                  /*!<@brief Device name: GPIOB */
#define BOARD_INITPINS_OFF_SWITCH_SIGNAL GPIO                       /*!<@brief GPIOB signal: GPIO */
#define BOARD_INITPINS_OFF_SWITCH_GPIO GPIOB                        /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_OFF_SWITCH_GPIO_PIN 1U                       /*!<@brief PORTB pin index: 1 */
#define BOARD_INITPINS_OFF_SWITCH_PORT PORTE                        /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_OFF_SWITCH_PIN 1U                            /*!<@brief PORTE pin index: 1 */
#define BOARD_INITPINS_OFF_SWITCH_CHANNEL 1                         /*!<@brief GPIOB GPIO channel: 1 */
#define BOARD_INITPINS_OFF_SWITCH_PIN_NAME PTE1                     /*!<@brief Pin name */
#define BOARD_INITPINS_OFF_SWITCH_LABEL "OFF_SWITCH"                /*!<@brief Label */
#define BOARD_INITPINS_OFF_SWITCH_NAME "OFF_SWITCH"                 /*!<@brief Identifier name */
#define BOARD_INITPINS_OFF_SWITCH_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                    /* @} */

/*! @name PTE2 (number 38), POWER_CTRL
  @{ */
#define BOARD_INITPINS_POWER_CTRL_PERIPHERAL GPIOB                   /*!<@brief Device name: GPIOB */
#define BOARD_INITPINS_POWER_CTRL_SIGNAL GPIO                        /*!<@brief GPIOB signal: GPIO */
#define BOARD_INITPINS_POWER_CTRL_GPIO GPIOB                         /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_POWER_CTRL_GPIO_PIN 2U                        /*!<@brief PORTB pin index: 2 */
#define BOARD_INITPINS_POWER_CTRL_PORT PORTE                         /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_POWER_CTRL_PIN 2U                             /*!<@brief PORTE pin index: 2 */
#define BOARD_INITPINS_POWER_CTRL_CHANNEL 2                          /*!<@brief GPIOB GPIO channel: 2 */
#define BOARD_INITPINS_POWER_CTRL_PIN_NAME PTE2                      /*!<@brief Pin name */
#define BOARD_INITPINS_POWER_CTRL_LABEL "POWER_CTRL"                 /*!<@brief Label */
#define BOARD_INITPINS_POWER_CTRL_NAME "POWER_CTRL"                  /*!<@brief Identifier name */
#define BOARD_INITPINS_POWER_CTRL_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                     /* @} */

/*! @name PTD5 (number 18), P_KDAT
  @{ */
#define BOARD_INITPINS_P_KDAT_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_P_KDAT_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_P_KDAT_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_P_KDAT_GPIO_PIN 29U     /*!<@brief PORTA pin index: 29 */
#define BOARD_INITPINS_P_KDAT_PORT PORTD       /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_P_KDAT_PIN 5U           /*!<@brief PORTD pin index: 5 */
#define BOARD_INITPINS_P_KDAT_CHANNEL 29       /*!<@brief GPIOA GPIO channel: 29 */
#define BOARD_INITPINS_P_KDAT_PIN_NAME PTD5    /*!<@brief Pin name */
#define BOARD_INITPINS_P_KDAT_LABEL "P_KDAT"   /*!<@brief Label */
#define BOARD_INITPINS_P_KDAT_NAME "P_KDAT"    /*!<@brief Identifier name */
                                               /* @} */

/*! @name PTC1 (number 19), P_KCLK
  @{ */
#define BOARD_INITPINS_P_KCLK_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_P_KCLK_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_P_KCLK_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_P_KCLK_GPIO_PIN 17U     /*!<@brief PORTA pin index: 17 */
#define BOARD_INITPINS_P_KCLK_PORT PORTC       /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_P_KCLK_PIN 1U           /*!<@brief PORTC pin index: 1 */
#define BOARD_INITPINS_P_KCLK_CHANNEL 17       /*!<@brief GPIOA GPIO channel: 17 */
#define BOARD_INITPINS_P_KCLK_PIN_NAME PTC1    /*!<@brief Pin name */
#define BOARD_INITPINS_P_KCLK_LABEL "P_KCLK"   /*!<@brief Label */
#define BOARD_INITPINS_P_KCLK_NAME "P_KCLK"    /*!<@brief Identifier name */
                                               /* @} */

/*! @name PTC0 (number 20), P_ARCK
  @{ */
#define BOARD_INITPINS_P_ARCK_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_P_ARCK_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_P_ARCK_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_P_ARCK_GPIO_PIN 16U     /*!<@brief PORTA pin index: 16 */
#define BOARD_INITPINS_P_ARCK_PORT PORTC       /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_P_ARCK_PIN 0U           /*!<@brief PORTC pin index: 0 */
#define BOARD_INITPINS_P_ARCK_CHANNEL 16       /*!<@brief GPIOA GPIO channel: 16 */
#define BOARD_INITPINS_P_ARCK_PIN_NAME PTC0    /*!<@brief Pin name */
#define BOARD_INITPINS_P_ARCK_LABEL "P_ARCK"   /*!<@brief Label */
#define BOARD_INITPINS_P_ARCK_NAME "P_ARCK"    /*!<@brief Identifier name */
                                               /* @} */

/*! @name PTA1 (number 34), P_ENA
  @{ */
#define BOARD_INITPINS_P_ENA_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_P_ENA_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_P_ENA_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_P_ENA_GPIO_PIN 1U      /*!<@brief PORTA pin index: 1 */
#define BOARD_INITPINS_P_ENA_PORT PORTA       /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_P_ENA_PIN 1U           /*!<@brief PORTA pin index: 1 */
#define BOARD_INITPINS_P_ENA_CHANNEL 1        /*!<@brief GPIOA GPIO channel: 1 */
#define BOARD_INITPINS_P_ENA_PIN_NAME PTA1    /*!<@brief Pin name */
#define BOARD_INITPINS_P_ENA_LABEL "P_ENA"    /*!<@brief Label */
#define BOARD_INITPINS_P_ENA_NAME "P_ENA"     /*!<@brief Identifier name */
                                              /* @} */

/*! @name PTB2 (number 22), P_ASCK
  @{ */
#define BOARD_INITPINS_P_ASCK_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_P_ASCK_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_P_ASCK_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_P_ASCK_GPIO_PIN 10U     /*!<@brief PORTA pin index: 10 */
#define BOARD_INITPINS_P_ASCK_PORT PORTB       /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_P_ASCK_PIN 2U           /*!<@brief PORTB pin index: 2 */
#define BOARD_INITPINS_P_ASCK_CHANNEL 10       /*!<@brief GPIOA GPIO channel: 10 */
#define BOARD_INITPINS_P_ASCK_PIN_NAME PTB2    /*!<@brief Pin name */
#define BOARD_INITPINS_P_ASCK_LABEL "P_ASCK"   /*!<@brief Label */
#define BOARD_INITPINS_P_ASCK_NAME "P_ASCK"    /*!<@brief Identifier name */
                                               /* @} */

/*! @name PTB3 (number 21), P_ADAT
  @{ */
#define BOARD_INITPINS_P_ADAT_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_P_ADAT_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_P_ADAT_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_P_ADAT_GPIO_PIN 11U     /*!<@brief PORTA pin index: 11 */
#define BOARD_INITPINS_P_ADAT_PORT PORTB       /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_P_ADAT_PIN 3U           /*!<@brief PORTB pin index: 3 */
#define BOARD_INITPINS_P_ADAT_CHANNEL 11       /*!<@brief GPIOA GPIO channel: 11 */
#define BOARD_INITPINS_P_ADAT_PIN_NAME PTB3    /*!<@brief Pin name */
#define BOARD_INITPINS_P_ADAT_LABEL "P_ADAT"   /*!<@brief Label */
#define BOARD_INITPINS_P_ADAT_NAME "P_ADAT"    /*!<@brief Identifier name */
                                               /* @} */

/*! @name PTC6 (number 37), KEYSCAN1
  @{ */
#define BOARD_INITPINS_KEYSCAN1_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_KEYSCAN1_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_KEYSCAN1_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_KEYSCAN1_GPIO_PIN 22U                      /*!<@brief PORTA pin index: 22 */
#define BOARD_INITPINS_KEYSCAN1_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_KEYSCAN1_PIN 6U                            /*!<@brief PORTC pin index: 6 */
#define BOARD_INITPINS_KEYSCAN1_CHANNEL 22                        /*!<@brief GPIOA GPIO channel: 22 */
#define BOARD_INITPINS_KEYSCAN1_PIN_NAME PTC6                     /*!<@brief Pin name */
#define BOARD_INITPINS_KEYSCAN1_LABEL "KEYSCAN1"                  /*!<@brief Label */
#define BOARD_INITPINS_KEYSCAN1_NAME "KEYSCAN1"                   /*!<@brief Identifier name */
#define BOARD_INITPINS_KEYSCAN1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                  /* @} */

/*! @name PTD6 (number 17), KEYSCAN3
  @{ */
#define BOARD_INITPINS_KEYSCAN3_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_KEYSCAN3_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_KEYSCAN3_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_KEYSCAN3_GPIO_PIN 30U                      /*!<@brief PORTA pin index: 30 */
#define BOARD_INITPINS_KEYSCAN3_PORT PORTD                        /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_KEYSCAN3_PIN 6U                            /*!<@brief PORTD pin index: 6 */
#define BOARD_INITPINS_KEYSCAN3_CHANNEL 30                        /*!<@brief GPIOA GPIO channel: 30 */
#define BOARD_INITPINS_KEYSCAN3_PIN_NAME PTD6                     /*!<@brief Pin name */
#define BOARD_INITPINS_KEYSCAN3_LABEL "KEYSCAN3"                  /*!<@brief Label */
#define BOARD_INITPINS_KEYSCAN3_NAME "KEYSCAN3"                   /*!<@brief Identifier name */
#define BOARD_INITPINS_KEYSCAN3_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                  /* @} */

/*! @name PTD7 (number 16), KEYSCAN2
  @{ */
#define BOARD_INITPINS_KEYSCAN2_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_KEYSCAN2_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_KEYSCAN2_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_KEYSCAN2_GPIO_PIN 31U                      /*!<@brief PORTA pin index: 31 */
#define BOARD_INITPINS_KEYSCAN2_PORT PORTD                        /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_KEYSCAN2_PIN 7U                            /*!<@brief PORTD pin index: 7 */
#define BOARD_INITPINS_KEYSCAN2_CHANNEL 31                        /*!<@brief GPIOA GPIO channel: 31 */
#define BOARD_INITPINS_KEYSCAN2_PIN_NAME PTD7                     /*!<@brief Pin name */
#define BOARD_INITPINS_KEYSCAN2_LABEL "KEYSCAN2"                  /*!<@brief Label */
#define BOARD_INITPINS_KEYSCAN2_NAME "KEYSCAN2"                   /*!<@brief Identifier name */
#define BOARD_INITPINS_KEYSCAN2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                  /* @} */

/*! @name PTD0 (number 2), ENCODER2
  @{ */
#define BOARD_INITPINS_ENCODER2_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_ENCODER2_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_ENCODER2_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_ENCODER2_GPIO_PIN 24U     /*!<@brief PORTA pin index: 24 */
#define BOARD_INITPINS_ENCODER2_PORT PORTD       /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_ENCODER2_PIN 0U           /*!<@brief PORTD pin index: 0 */
#define BOARD_INITPINS_ENCODER2_CHANNEL 24       /*!<@brief GPIOA GPIO channel: 24 */
#define BOARD_INITPINS_ENCODER2_PIN_NAME PTD0    /*!<@brief Pin name */
#define BOARD_INITPINS_ENCODER2_LABEL "ENCODER2" /*!<@brief Label */
#define BOARD_INITPINS_ENCODER2_NAME "ENCODER2"  /*!<@brief Identifier name */
                                                 /* @} */

/*! @name PTD1 (number 1), ENCODER1
  @{ */
#define BOARD_INITPINS_ENCODER1_PERIPHERAL GPIOA /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_ENCODER1_SIGNAL GPIO      /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_ENCODER1_GPIO GPIOA       /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_ENCODER1_GPIO_PIN 25U     /*!<@brief PORTA pin index: 25 */
#define BOARD_INITPINS_ENCODER1_PORT PORTD       /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_ENCODER1_PIN 1U           /*!<@brief PORTD pin index: 1 */
#define BOARD_INITPINS_ENCODER1_CHANNEL 25       /*!<@brief GPIOA GPIO channel: 25 */
#define BOARD_INITPINS_ENCODER1_PIN_NAME PTD1    /*!<@brief Pin name */
#define BOARD_INITPINS_ENCODER1_LABEL "ENCODER1" /*!<@brief Label */
#define BOARD_INITPINS_ENCODER1_NAME "ENCODER1"  /*!<@brief Identifier name */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
