/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: MKE02Z64xxx4
package_id: MKE02Z64VLD4
mcu_data: ksdk2_0
processor_version: 3.0.0
pin_labels:
- {pin_num: '12', pin_signal: PTB5/FTM2_CH5/SPI0_PCS0/ACMP1_OUT, label: LED1, identifier: LED1}
- {pin_num: '14', pin_signal: PTC3/FTM2_CH3/ADC0_SE11, label: LED2, identifier: LED2}
- {pin_num: '15', pin_signal: PTC2/FTM2_CH2/ADC0_SE10, label: LED3, identifier: LED3}
- {pin_num: '38', pin_signal: PTE2/SPI0_MISO, label: POWER_CTRL, identifier: POWER_CTRL}
- {pin_num: '39', pin_signal: PTE1/SPI0_MOSI, label: OFF_SWITCH, identifier: OFF_SWITCH}
- {pin_num: '18', pin_signal: PTD5/KBI1_P5, label: P_KDAT, identifier: P_KDAT}
- {pin_num: '19', pin_signal: PTC1/FTM2_CH1/ADC0_SE9, label: P_KCLK, identifier: P_KCLK}
- {pin_num: '20', pin_signal: PTC0/FTM2_CH0/ADC0_SE8, label: P_ARCK, identifier: P_ARCK}
- {pin_num: '21', pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7, label: P_ADAT, identifier: P_ADAT}
- {pin_num: '22', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6, label: P_ASCK, identifier: P_ASCK}
- {pin_num: '34', pin_signal: PTA1/KBI0_P1/FTM0_CH1/ACMP0_IN1/ADC0_SE1, label: P_ENA, identifier: P_ENA}
- {pin_num: '37', pin_signal: PTC6/UART1_RX, label: KEYSCAN1, identifier: KEYSCAN1}
- {pin_num: '16', pin_signal: PTD7/KBI1_P7/UART2_TX, label: KEYSCAN2, identifier: KEYSCAN2}
- {pin_num: '17', pin_signal: PTD6/KBI1_P6/UART2_RX, label: KEYSCAN3, identifier: KEYSCAN3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '12', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTB5/FTM2_CH5/SPI0_PCS0/ACMP1_OUT}
  - {pin_num: '15', peripheral: GPIOA, signal: 'GPIO, 18', pin_signal: PTC2/FTM2_CH2/ADC0_SE10}
  - {pin_num: '14', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: PTC3/FTM2_CH3/ADC0_SE11}
  - {pin_num: '9', peripheral: OSC, signal: EXTAL, pin_signal: PTB7/I2C0_SCL/EXTAL}
  - {pin_num: '10', peripheral: OSC, signal: XTAL, pin_signal: PTB6/I2C0_SDA/XTAL}
  - {pin_num: '39', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: PTE1/SPI0_MOSI, direction: INPUT, high_drive_enable: disable, pullup_enable: enable}
  - {pin_num: '38', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: PTE2/SPI0_MISO, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTD5/KBI1_P5}
  - {pin_num: '19', peripheral: GPIOA, signal: 'GPIO, 17', pin_signal: PTC1/FTM2_CH1/ADC0_SE9}
  - {pin_num: '20', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: PTC0/FTM2_CH0/ADC0_SE8}
  - {pin_num: '34', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/KBI0_P1/FTM0_CH1/ACMP0_IN1/ADC0_SE1}
  - {pin_num: '22', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6}
  - {pin_num: '21', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7}
  - {pin_num: '37', peripheral: GPIOA, signal: 'GPIO, 22', pin_signal: PTC6/UART1_RX, direction: INPUT, pullup_enable: enable}
  - {pin_num: '17', peripheral: GPIOA, signal: 'GPIO, 30', pin_signal: PTD6/KBI1_P6/UART2_RX, direction: INPUT, pullup_enable: enable}
  - {pin_num: '16', peripheral: GPIOA, signal: 'GPIO, 31', pin_signal: PTD7/KBI1_P7/UART2_TX, direction: INPUT, pullup_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* High Current Drive Capability of PTE1: 0x00u */
    PORT_SetHighDriveEnable(PORT, kPORT_HighDrive_PTE1, 0);
    /* Pull Enable for Port E Bit 1: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTE, kPORT_PinIdx1, 1);
    /* Pull Enable for Port C Bit 6: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTC, kPORT_PinIdx6, 1);
    /* Pull Enable for Port D Bit 6: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, kPORT_PinIdx6, 1);
    /* Pull Enable for Port D Bit 7: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, kPORT_PinIdx7, 1);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
