/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: MKE02Z64xxx4
package_id: MKE02Z64VLD4
mcu_data: ksdk2_0
processor_version: 3.0.0
pin_labels:
- {pin_num: '12', pin_signal: PTB5/FTM2_CH5/SPI0_PCS0/ACMP1_OUT, label: LED1, identifier: LED1}
- {pin_num: '14', pin_signal: PTC3/FTM2_CH3/ADC0_SE11, label: LED2, identifier: LED2}
- {pin_num: '15', pin_signal: PTC2/FTM2_CH2/ADC0_SE10, label: LED3, identifier: LED3}
- {pin_num: '38', pin_signal: PTE2/SPI0_MISO, label: POWER_CTRL, identifier: POWER_CTRL}
- {pin_num: '39', pin_signal: PTE1/SPI0_MOSI, label: OFF_SWITCH, identifier: OFF_SWITCH}
- {pin_num: '18', pin_signal: PTD5/KBI1_P5, label: P_KDAT, identifier: P_KDAT}
- {pin_num: '19', pin_signal: PTC1/FTM2_CH1/ADC0_SE9, label: P_KCLK, identifier: P_KCLK}
- {pin_num: '20', pin_signal: PTC0/FTM2_CH0/ADC0_SE8, label: P_ARCK, identifier: P_ARCK}
- {pin_num: '21', pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7, label: P_ADAT, identifier: P_ADAT}
- {pin_num: '22', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6, label: P_ASCK, identifier: P_ASCK}
- {pin_num: '34', pin_signal: PTA1/KBI0_P1/FTM0_CH1/ACMP0_IN1/ADC0_SE1, label: P_ENA, identifier: P_ENA}
- {pin_num: '37', pin_signal: PTC6/UART1_RX, label: KEYSCAN1, identifier: KEYSCAN1}
- {pin_num: '16', pin_signal: PTD7/KBI1_P7/UART2_TX, label: KEYSCAN2, identifier: KEYSCAN2}
- {pin_num: '17', pin_signal: PTD6/KBI1_P6/UART2_RX, label: KEYSCAN3, identifier: KEYSCAN3}
- {pin_num: '1', pin_signal: PTD1/KBI1_P1/FTM2_CH3/SPI1_MOSI, label: ENCODER1, identifier: ENCODER1}
- {pin_num: '2', pin_signal: PTD0/KBI1_P0/FTM2_CH2/SPI1_SCK, label: ENCODER2, identifier: ENCODER2}
- {pin_num: '26', pin_signal: PTA6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2, label: GATEOUT4, identifier: GATEOUT4}
- {pin_num: '29', pin_signal: PTD4/KBI1_P4, label: GATEOUT3, identifier: GATEOUT3}
- {pin_num: '30', pin_signal: PTD3/KBI1_P3/SPI1_PCS0, label: GATEOUT2, identifier: GATEOUT2}
- {pin_num: '31', pin_signal: PTD2/KBI1_P2/SPI1_MISO, label: GATEOUT1, identifier: GATEOUT1}
- {pin_num: '35', pin_signal: PTA0/KBI0_P0/FTM0_CH0/ACMP0_IN0/ADC0_SE0, label: EXTSYNC, identifier: EXTSYNC}
- {pin_num: '41', pin_signal: PTC5/FTM1_CH1/RTCO, label: SYNCOUT, identifier: SYNCOUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '12', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTB5/FTM2_CH5/SPI0_PCS0/ACMP1_OUT}
  - {pin_num: '15', peripheral: GPIOA, signal: 'GPIO, 18', pin_signal: PTC2/FTM2_CH2/ADC0_SE10}
  - {pin_num: '14', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: PTC3/FTM2_CH3/ADC0_SE11}
  - {pin_num: '39', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: PTE1/SPI0_MOSI, direction: INPUT, high_drive_enable: disable, pullup_enable: enable}
  - {pin_num: '38', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: PTE2/SPI0_MISO, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTD5/KBI1_P5}
  - {pin_num: '19', peripheral: GPIOA, signal: 'GPIO, 17', pin_signal: PTC1/FTM2_CH1/ADC0_SE9}
  - {pin_num: '20', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: PTC0/FTM2_CH0/ADC0_SE8}
  - {pin_num: '34', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/KBI0_P1/FTM0_CH1/ACMP0_IN1/ADC0_SE1}
  - {pin_num: '22', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6}
  - {pin_num: '21', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7}
  - {pin_num: '37', peripheral: GPIOA, signal: 'GPIO, 22', pin_signal: PTC6/UART1_RX, direction: INPUT, pullup_enable: enable}
  - {pin_num: '17', peripheral: GPIOA, signal: 'GPIO, 30', pin_signal: PTD6/KBI1_P6/UART2_RX, direction: INPUT, pullup_enable: enable}
  - {pin_num: '16', peripheral: GPIOA, signal: 'GPIO, 31', pin_signal: PTD7/KBI1_P7/UART2_TX, direction: INPUT, pullup_enable: enable}
  - {pin_num: '2', peripheral: GPIOA, signal: 'GPIO, 24', pin_signal: PTD0/KBI1_P0/FTM2_CH2/SPI1_SCK, pullup_enable: enable}
  - {pin_num: '1', peripheral: GPIOA, signal: 'GPIO, 25', pin_signal: PTD1/KBI1_P1/FTM2_CH3/SPI1_MOSI, pullup_enable: enable}
  - {pin_num: '9', peripheral: OSC, signal: EXTAL, pin_signal: PTB7/I2C0_SCL/EXTAL}
  - {pin_num: '10', peripheral: OSC, signal: XTAL, pin_signal: PTB6/I2C0_SDA/XTAL}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2}
  - {pin_num: '31', peripheral: GPIOA, signal: 'GPIO, 26', pin_signal: PTD2/KBI1_P2/SPI1_MISO}
  - {pin_num: '30', peripheral: GPIOA, signal: 'GPIO, 27', pin_signal: PTD3/KBI1_P3/SPI1_PCS0}
  - {pin_num: '29', peripheral: GPIOA, signal: 'GPIO, 28', pin_signal: PTD4/KBI1_P4}
  - {pin_num: '32', peripheral: I2C0, signal: SCL, pin_signal: PTA3/KBI0_P3/UART0_TX/I2C0_SCL}
  - {pin_num: '33', peripheral: I2C0, signal: SDA, pin_signal: PTA2/KBI0_P2/UART0_RX/I2C0_SDA}
  - {pin_num: '24', peripheral: UART0, signal: RX, pin_signal: PTB0/KBI0_P4/UART0_RX/ADC0_SE4}
  - {pin_num: '23', peripheral: UART0, signal: TX, pin_signal: PTB1/KBI0_P5/UART0_TX/ADC0_SE5}
  - {pin_num: '35', peripheral: KBI0, signal: 'P, 0', pin_signal: PTA0/KBI0_P0/FTM0_CH0/ACMP0_IN0/ADC0_SE0, pullup_enable: disable}
  - {pin_num: '41', peripheral: GPIOA, signal: 'GPIO, 21', pin_signal: PTC5/FTM1_CH1/RTCO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* High Current Drive Capability of PTE1: 0x00u */
    PORT_SetHighDriveEnable(PORT, kPORT_HighDrive_PTE1, 0);
    /* Pull Enable for Port E Bit 1: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTE, kPORT_PinIdx1, 1);
    /* Pull Enable for Port A Bit 0: 0x00u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTA, kPORT_PinIdx0, 0);
    /* Pull Enable for Port C Bit 6: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTC, kPORT_PinIdx6, 1);
    /* Pull Enable for Port D Bit 0: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, kPORT_PinIdx0, 1);
    /* Pull Enable for Port D Bit 1: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, kPORT_PinIdx1, 1);
    /* Pull Enable for Port D Bit 6: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, kPORT_PinIdx6, 1);
    /* Pull Enable for Port D Bit 7: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, kPORT_PinIdx7, 1);
    /* pin 33,32 is configured as I2C0_SDA, I2C0_SCL */
    PORT_SetPinSelect(kPORT_I2C0, kPORT_I2C0_SCLPTA3_SDAPTA2);
    /* pin 23,24 is configured as UART0_TX, UART0_RX */
    PORT_SetPinSelect(kPORT_UART0, kPORT_UART0_RXPTB0_TXPTB1);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
