/*
 * params.h
 *
 *  Created on: 12 Mar 2018
 *      Author: jason
 */

#ifndef PARAMS_H_
#define PARAMS_H_

typedef enum {
	P_NONE = 0,

	P_SQL_SEQ_MODE,
	P_SQL_STEP_RATE,
	P_SQL_MIDI_CHAN,
	P_SQL_MIDI_CC,
	P_SQL_MAX,

	P_CVGATE_VSCALE,
	P_CVGATE_VRANGE,
	P_CVGATE_MAX


} PARAM_ID;


enum {
	V_SQL_SEQ_MODE_NOTE = 0,
	V_SQL_SEQ_MODE_MOD,
	V_SQL_SEQ_MODE_VEL,
	V_SQL_SEQ_MODE_TRANSPOSE,
	V_SQL_SEQ_MODE_MAX,
};

enum {
	V_SQL_STEP_RATE_1 = 0,
	V_SQL_STEP_RATE_2D,
	V_SQL_STEP_RATE_2,
	V_SQL_STEP_RATE_4D,
	V_SQL_STEP_RATE_2T,
	V_SQL_STEP_RATE_4,
	V_SQL_STEP_RATE_8D,
	V_SQL_STEP_RATE_4T,
	V_SQL_STEP_RATE_8,
	V_SQL_STEP_RATE_16D,
	V_SQL_STEP_RATE_8T,
	V_SQL_STEP_RATE_16,
	V_SQL_STEP_RATE_16T,
	V_SQL_STEP_RATE_32,
	V_SQL_STEP_RATE_MAX
};

enum {
	V_CVGATE_VSCALE_1VOCT = 0,
	V_CVGATE_VSCALE_1_2VOCT,
	V_CVGATE_VSCALE_HZVOLT,
	V_CVGATE_VSCALE_MAX
};

enum {
	V_SQL_STEP_TRIG_CLOCK = 0,
	V_SQL_STEP_TRIG_LAYER1,
	V_SQL_STEP_TRIG_LAYER2,
	V_SQL_STEP_TRIG_LAYER3,
	V_SQL_STEP_TRIG_LAYER4,
	V_SQL_STEP_TRIG_MAX
};

enum {
	V_SQL_RESET_TRIG_NONE = 0,
	V_SQL_RESET_TRIG_LAYER1,
	V_SQL_RESET_TRIG_LAYER2,
	V_SQL_RESET_TRIG_LAYER3,
	V_SQL_RESET_TRIG_LAYER4,
	V_SQL_RESET_TRIG_MAX
};

enum {
	V_SQL_TRANSP_SRC_NONE = 0,
	V_SQL_TRANSP_SRC_LAYER1,
	V_SQL_TRANSP_SRC_LAYER2,
	V_SQL_TRANSP_SRC_LAYER3,
	V_SQL_TRANSP_SRC_LAYER4,
	V_SQL_TRANSP_SRC_MAX
};


extern void set_param(PARAM_ID param, int value);
extern int get_param(PARAM_ID param);




#endif /* PARAMS_H_ */
